name: github_repo_app
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  go_router: ^14.3.0
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  get_it: ^7.6.4
  injectable: ^2.3.2
  injectable_generator: ^2.4.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  json_serializable: ^6.9.0
  intl:
  animated_text_kit:
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg:
  dio: ^5.7.0
  pretty_dio_logger: ^1.4.0
  logger: ^2.5.0
  dartz: ^0.10.1
  mocktail: ^1.0.4
  retrofit: ^4.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.6
  freezed: ^2.4.5
  bloc_test: ^9.1.5
  retrofit_generator: ^9.1.0



flutter:
  uses-material-design: true

